### ISSUE TITLE
Save figures with ggsave

### ISSUE THREAD

**Issue by cdjemiel** [mjskay/ggblend#11]
Hi mjskay,

I would like to save the plots made with ggplot and ggblend.

When I use ggsave for my plot (geom_point), I don't have the points and just the grid.
My warnings 
blend = "darken" does not appear to be supported by your graphics device.
 - Blending output may not be as expected.
 - If your current graphics device *does* support blend = "darken"
   but auto-detection failed, consider reporting a bug. 

and 

In drawDetails.GridGroup(x, recording = FALSE) : Group definition failed

I already had a display problem in Rstudio (MacOS) but this works after putting the backend of my graphic device in cairo.

![test](https://user-images.githubusercontent.com/18189336/169261339-e66ada1c-04cd-4f16-8b85-2742f09397e3.png)

Can you tell me how to properly save my plot please?

Best regards

Christophe

**Comment by mjskay** [comment]
Yeah, if you are saving with `ggsave()` you will have to make sure it is using the cairo device as well. Can you try passing `type = "cairo"` to `ggsave()`?

**Comment by cdjemiel** [comment]
Yep, it works with `type = "cairo"`. 

Thanks
