### ISSUE TITLE
Compatibility with ggnewscale

### ISSUE THREAD

**Issue by mjskay** [mjskay/ggblend#14]
Check for compatibility with ggnewscale. See https://twitter.com/dr_xeo/status/1551108655852015617?t=MZC4Fc3VHdvj_kd3NwY70A&s=19

**Comment by stephenwilliams22** [comment]
@mjskay Thanks for this awesome new package! I was checking in to see if there is any progress here? I've been able to recreate the plot in the tweet for a discrete scale but have not had success using multiple continuous scales. Here's an example that I came up with to draw two overlapping circles that I'd like to blend. On a discrete scale things work great
```
x <- data.frame(x = c(1.95,2.05),
                y = c(2,2),
                circle = c("a", "b"))
x %>% 
  ggplot(aes(x = x, y = y, color = circle)) + 
  geom_point(size = 10) %>% blend("add")+
  scale_color_manual(values = c("red", "green"))+
  xlim(0,4) +
  ylim(0,4) + 
  theme_bw()
```

![image](https://user-images.githubusercontent.com/24922527/208278716-107e6a5e-08d4-4ab1-9cb9-30d8fe6d80aa.png)

But with a continuous scale there is an issue with `relayer` I believe (I know this isn't your problem). 

```
x <- data.frame(x = c(1.95,2.05),
                y = c(2,2),
                value = c(2,1),
                circle = c("a", "b"))

x %>% 
  ggplot(aes(x, y)) +
list(
  geom_point(data = x %>% filter(circle == "a"), aes(color = value), size = 10),
  geom_point(data = x %>% filter(circle == "b"), aes(color2 = value), size = 10) %>% 
    rename_geom_aes(new_aes = c("colour" = "colour2"))
  ) %>% blend("add")+
  scale_color_gradientn(colors = paletteer_c("ggthemes::Classic Blue", 30), limits = c(0,5), aesthetics = "colour2")+
  scale_color_gradientn(colors = paletteer_c("ggthemes::Red", 30), limits = c(0,5)) +
  xlim(0,4) +
  ylim(0,4) + 
  theme_bw()
```

It would be amazing to have compatibility of `ggblend` with different continuous scales.

**Comment by mjskay** [comment]
ah yeah, at the moment I haven't had a chance to return to this... been working on some ggdist stuff and now the quarter's started up again I will probably not have a lot of time until the summer. Is definitely on my list though! Just might be awhile unless someone else takes a look... sorry!

**Comment by mjskay** [comment]
@stephenwilliams22 the example you gave on continuous scales works fine for me as long as I add `guide = "none"` to the first call to `scale_color_gradientn()`.

Re: ggnewscale, I've investigated it more, and it is unlikely to work correctly with ggblend. The problem is that ggnewscale changes scales by modifying the ggplot object itself, not through local modification to layers. ggblend would require it to make local modifications to layers so that the resulting layers can then be blended.

So I think the solutions to using multiple scales with ggblend would be: (1) a change in how ggnewscale works (@eliocamp?), (2) using relayer, or (3) implementing a local-layer scale modification scheme in ggblend (which is not strictly out of the question).

**Comment by eliocamp** [comment]
I have the vague recollection of looking into this a while ago and concluding that it was a hard problem. But I don't remember why. 

ggnewscale works by modifying geoms and scales to use a different aes. So if you add `new_scale_color()`, all the previous geoms that took the `color` aesthetic are modified to actually use `color_new` (or something like that). I don't know if you would call that "local modification of layers". The result is (or should be) the same as if the user were to create their own geoms and add them to the plot. 

I don't have a working understanding of ggblend (any more, I guess?). If it relies on strict naming of aes, it will not be compatible with ggnewscale; with ggnewscale affected geoms don't have a `colour` aesthetic any more, so if ggblend looks for it, it will not find it.

**Comment by eliocamp** [comment]
What if ggnewscale could recognise and change the dummy ggblend layer appropriately?

**Comment by mjskay** [comment]
Hmmm maybe that could work. {ggblend} adds a `"HiddenLayer"` class to those layers, so they are at least identifiable. One option would be to add some kind of interface for "replacing" or "updating" a layer, which {ggblend} could then provide an implementation of for `"HiddenLayer"` objects (since I think what would need to happen is that the `"HiddenLayer"` would keep around a reference to the blend layer and vice versa, and then the `"HiddenLayer"` would have to update the reference back to itself in the blend layer when the `"HiddenLayer"` is replaced... not sure if there's a simpler solution).

**Comment by mjskay** [comment]
yeah, thinking about this more, I think a solution that divides responsibility appropriately between packages would be something like:

- {ggnewscale} adds a generic function like `update_layer(old_layer, constructor)` where `constructor` is a function that takes a layer and returns a new one. The default implementation would be very simple, something like `update_layer.default = function(old_layer, constructor) { constructor(old_layer) }`. {ggnewscale} would use this function to create updated versions of layers.
- {ggblend} could then implement `update_layer.HiddenLayer` to do the various annoying bits of making sure the dummy layers are properly updated inside the blending layer.

If you want I can prototype this and if it works submit a PR to ggnewscale for the changes, which I suspect should be minor there (since the more annoying bits will live in {ggblend})

**Comment by eliocamp** [comment]
I think it makes sense. It's not far off from how ggnewscale already works. I can make the required refactor and ping you here when its done.

**Comment by mjskay** [comment]
sounds great!

**Comment by mjskay** [comment]
Oh, nevermind! I figured out that everything does actually work as is, I just had to fix a bug in how I was manipulating lists of layers that accidentally stripped the class from the output of `new_scale_color()`.

A silly example of both packages working together now:

```r
data.frame(x = 1, y = 1, g = c("a","b"), h = c("d", "e")) |>
  ggplot(aes(x, y, shape = g)) +
  list(
    geom_point(aes(color = g), size = 20),
    scale_color_brewer(palette = "Set1"),
    new_scale_color(),
    geom_point(aes(color = h, x = 1.5), size = 20)
  ) * blend("multiply") +
  scale_color_brewer(palette = "Set2") +
  guides(shape = "none") +
  coord_cartesian(xlim = c(0.5, 2))
```
![image](https://github.com/mjskay/ggblend/assets/6345019/a7384614-252e-4d5a-8ce5-072a1fcd502b)

So, no need for hacky workarounds to layer updating! Will close this now :).

**Comment by eliocamp** [comment]
Oh fantastic! 🤩

**Comment by stephenwilliams22** [comment]
Thanks guys. This is great!
