### ISSUE TITLE
Blend option for ggplot color aes

### ISSUE THREAD

**Issue by Anacristina0914** [mjskay/ggblend#19]
First of all, thank you for this great package. I am currently working in single-cell transcriptomics, and often plotting a UMAP representation of cells along with the expression of two (or more) genes can be a problem, as one can mask the other and make it seem like the expression of one gene is higher than the other simply because of the order in which they were plotted -- As noted in your documentation, draw order matters. 

I was wondering if it's possible to use this tool to merge ggplots in which 2 aes colours have been used. For example:

```r
ggplot1 <- ggplot(df, aes(x = coord_x, y = coord_y, color = var1) + geom_point() +
scale_color_continuous(low = "blue", high = "black")
ggplot2 <- ggplot(df, aes(x = coord_x, y = coord_y, color = var2) + geom_point() +
scale_color_continuous(low = "yellow", high = "red")
```
Where df contains 4 columns with the continuous variables: coord_x, coord_y, var1, var2. Thanks in advance!

- Ana C.

**Comment by mjskay** [comment]
You can do something like this by using ggblend with the ggnewscale package, which allows you to use multiple color scales in the same plot. Something like this:

```r
set.seed(1234)

library(ggplot2)
library(ggblend)

n = 100
df = mvtnorm::rmvnorm(n, c(0, 1), sigma = matrix(c(1,0.5,0.5,1), nrow = 2)) |>
  as.data.frame() |>
  setNames(c("var1", "var2")) |>
  transform(x = rnorm(n), y = rnorm(n))

df |> 
  ggplot(aes(x, y)) +
  list(
    geom_point(aes(color = var1)),
    scale_color_continuous(low = "white", high = "blue"),
    ggnewscale::new_scale_color(),
    geom_point(aes(color = var2)),
    scale_color_continuous(low = "white", high = "red")
  ) |> blend("multiply") +
  theme_light()
```
![image](https://github.com/mjskay/ggblend/assets/6345019/b32be885-4448-4e7b-af65-061e834cc113)

However, blending continuous color scales using this method in a way that people can perceive correctly is hard. You might be better off using a bivariate color scale, e.g. via something like the [multiscales](https://github.com/clauswilke/multiscales) package.

**Comment by Anacristina0914** [comment]
Thank you for your answer @mjskay. I agree, blending continuous scales is difficult in this case. Using a bivariate color scale may be a more suitable approach indeed. 

- Ana
