### ISSUE TITLE
ggblend on continuous scale

### ISSUE THREAD

**Issue by BiotechPedro** [mjskay/ggblend#21]
Hi!

FOA, thank you for the package! It's great, really.

Have you thought in making the blend compatible with multiple geoms? As an example, I would like to plot one numeric variable as a geom_point() with one color and blend it with another numeric variable in another geom_point() with a different color.

Do you thinks this would be feasible? 

Thanks!

Pedro

**Comment by mjskay** [comment]
That should work --- is there something specific you were trying to do that didn't work?

**Comment by BiotechPedro** [comment]
Sorry, I didn't think hard enough. Now I've done it and you're right, it's absolutely possible to blend multiple continuous variables! That's great.

IMHO, it would be very cool if you add this as an example in the package's web (e.g. Blending multiple geometries of continuous scale). 

In case you find this of help, here it's the [web](https://satijalab.org/seurat/articles/visualization_vignette#new-additions-to-featureplot) which contains the plot (search for "Visualize co-expression of two features simultaneously") I wanted to reproduce with your package, and below my code and visualization:

[coexpr_MS4A1_CD79A.pdf](https://github.com/mjskay/ggblend/files/14898123/coexpr_MS4A1_CD79A.pdf)

```r
library(Seurat)
library(SeuratData)
InstallData("pbmc3k")
pbmc3k.final <- LoadData("pbmc3k", type = "pbmc3k.final")

library(reshape2)
library(ggplot2)
library(ggblend)

df <- FetchData(pbmc3k.final, vars = c("MS4A1", "CD79A", "UMAP_1", "UMAP_2"))
df <- melt(df, id.vars = c("UMAP_1", "UMAP_2"))
ggplot(df, aes(x = UMAP_1, y = UMAP_2)) +
  list(geom_point(data = df[df$variable == "MS4A1", ], 
                  aes(color = value), size = 2.5),
        geom_point(data = df[df$variable == "CD79A", ], 
                   aes(fill = value), size = 2.5, 
                   pch = 21, color = alpha("gainsboro", 0.1))) |> 
  blend("overlay") +
  scale_color_gradient(low = alpha("gainsboro", 0.1), high = "red",
                       name = "MS4A1", limits = c(0, 4)) +
  scale_fill_gradient(low = alpha("gainsboro", 0.1), high = "green",
                      name = "CD79A", limits = c(0, 4)) +
  theme_void()
```

Best,

Pedro
