### ISSUE TITLE
experimental lifecycle

### ISSUE THREAD

**Issue by davidhodge931** [mjskay/ggblend#22]
Awesome package! 

I was wondering about using {ggblend} as a dependency in my R package {ggblanket} of ggplot2 wrapper functions, but then I noticed the lifecycle of {ggblend} is experimental. 

Assume this is still the case, and it'd be unwise to add {ggblend} as a dependency?

**Comment by mjskay** [comment]
Thanks! Good question.

I'd say it depends: `blend` and `adjust` (and operations based on it: `copy_over`, `copy_under`) are pretty stable. `partitition` is probably stable since if I decide to change its semantics I will likely just create a new function. `affine_transform` may change in the future.

What are you planning to use it for?

**Comment by mjskay** [comment]
(although for `blend` it may also depend on the operation, as I recall the usual blend modes like `"multiply"` and whatnot work in a consistent way, but I may need to adjust how some of the compositing operations work in the future... been awhile since I looked at those though)

**Comment by davidhodge931** [comment]
I think I just want to use ggblend::blend("multiply") in my package.

{ggblanket} is a bunch of ggplot2 wrapper functions. It tries to make it quicker/simper to plot much of what most people need from ggplot2, and also enable well-designed stuff by default.

Sometimes things overlap, which is not great. I thought if ggblend::blend("multiply") is stable, I could just add it into all of my functions - as this is pretty much what I think is optimal. 

<img width="680" alt="image" src="https://github.com/user-attachments/assets/74cf5d46-35a0-4f05-bd5b-edef79f1fb70">

**Comment by mjskay** [comment]
Oh yeah, that should be stable!

**Comment by mjskay** [comment]
np!
