### ISSUE TITLE
blend = "darken" does not appear to be supported

### ISSUE THREAD

**Issue by modche** [mjskay/ggblend#7]
1. Using R 4.2.0 and R Studio 2022.02.2 Build 485
2. Installed remotes::install_github("mjskay/ggblend")
3. Try to run examples from https://mjskay.github.io/ggblend/

I get an empty plot with warnings (...the first normal plot works fine)

<img width="519" alt="image" src="https://user-images.githubusercontent.com/13642619/167619757-aebc7173-2126-4d9e-aeec-5bc2b5a9536c.png">

```{r}
Warning messages:
1: blend = "darken" does not appear to be supported by your graphics device.
 - Blending output may not be as expected.
 - If your current graphics device *does* support blend = "darken"
   but auto-detection failed, consider reporting a bug. 
2: In drawDetails.GridGroup(x, recording = FALSE) :
  Group definition failed
3: In drawDetails.GridGroup(x, recording = FALSE) :
  Group definition failed
```

R Studio settings:
<img width="143" alt="image" src="https://user-images.githubusercontent.com/13642619/167619918-8269bf82-25fc-4fe5-bebf-73638ced8bc2.png">
(R Studio reboot and other graphic settings do not help)

```{r}
> sessionInfo()
R version 4.2.0 (2022-04-22)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Big Sur 11.6.5

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] forcats_0.5.1      stringr_1.4.0      dplyr_1.0.9        purrr_0.3.4        readr_2.1.2        tidyr_1.2.0       
 [7] tibble_3.1.7       tidyverse_1.3.1    ggblend_0.0.0.9000 ggplot2_3.3.6     

```

**Comment by mjskay** [comment]
Can you try changing the backend to "cairo"? I don't think ragg supports blending yet.

**Comment by modche** [comment]
Ah, after rebooting R and switching to 'cairo' it works, thanks!

**Comment by mjskay** [comment]
No problem!
