### ISSUE TITLE
Could anyone, please, confirm this warning?

### ISSUE THREAD

**Issue by nipnipj** [mjskay/ggblend#8]
I'm using R 4.2. I'm having the following warning
```
Warning messages:
1: blend = "darken" does not appear to be supported by your graphics device.
 - Blending output may not be as expected.
 - If your current graphics device *does* support blend = "darken"
   but auto-detection failed, consider reporting a bug. 
2: In drawDetails.GridGroup(x, recording = FALSE) :
  Group definition failed
```

**Comment by mjskay** [comment]
See here: #1

**Comment by nipnipj** [comment]
I'm using Linux mint OS. I can see the plots even with DEFAULT backend. I still get the warning with CAIRO and CAIRO PNG, tho.

**Comment by mjskay** [comment]
Ah yeah, I'm pretty sure that's a bug in the graphics devices. Some of them do not report that they support blending even though they do.

The easiest solution in this case is to just disable the warning with `options(ggblend.check_blend = FALSE)`. At some point I need to report the bug upstream. Hope that helps!
